image: itsplus/s2shape-test-harness

stages:
  - build
  - test

variables:
  HBASE_HOST: hbase
  HBASE_PORT: "8080"

before_script:
  - dotnet restore -s https://www.myget.org/F/s2/ -s https://api.nuget.org/v3/index.json

build:
  stage: build
  script:
    - dotnet build

test:
  stage: test
  services:
    - name: dajobe/hbase
      alias: hbase

  script:
    - ROOT_PROJECT_PATH=$(pwd)
    - dotnet build
    - dotnet publish
    - cd $ROOT_PROJECT_PATH/HBaseSupplyCollectorLoader/bin/Debug/netcoreapp2.2/publish
    - cp -f /SupplyCollectorDataLoader/SupplyCollectorDataLoader/bin/Debug/netcoreapp2.2/SupplyCollectorDataLoader.runtimeconfig.json .
    - dotnet SupplyCollectorDataLoader.dll -init HBaseSupplyCollector hbase://$HBASE_HOST:$HBASE_PORT
    - dotnet SupplyCollectorDataLoader.dll -xunit HBaseSupplyCollector hbase://$HBASE_HOST:$HBASE_PORT
    - cd $ROOT_PROJECT_PATH
    - dotnet test

load_test:
  stage: test
  services:
    - name: dajobe/hbase
      alias: hbase

  script:
    - ROOT_PROJECT_PATH=$(pwd)
    - dotnet build
    - dotnet publish
    - cd $ROOT_PROJECT_PATH/HBaseSupplyCollectorLoader/bin/Debug/netcoreapp2.2/publish
    - cp -f /SupplyCollectorDataLoader/SupplyCollectorDataLoader/bin/Debug/netcoreapp2.2/SupplyCollectorDataLoader.runtimeconfig.json .
    - dotnet SupplyCollectorDataLoader.dll -init HBaseSupplyCollector hbase://$HBASE_HOST:$HBASE_PORT
    - dotnet SupplyCollectorDataLoader.dll -xunit HBaseSupplyCollector hbase://$HBASE_HOST:$HBASE_PORT
    - dotnet SupplyCollectorDataLoader.dll -samples HBaseSupplyCollector hbase://$HBASE_HOST:$HBASE_PORT TestCollection Test1:int,Test2:string,Test3:bool,Test4:double,Test5 1000000
    - cd $ROOT_PROJECT_PATH/HBaseSupplyCollectorTests/bin/Debug/netcoreapp2.2/publish
    - SupplyCollectorTestHarness
